	SL no		Keywords (Questions)		Answers	
INSERT into chatbot VALUES (3,"admission process","The admission process involves filling out the application form, submitting required documents, and completing any entrance tests or interviews if applicable.	");
INSERT into chatbot VALUES (4,"eligibility","Eligibility criteria vary by program. Please specify the program or course to get detailed information.	");
INSERT into chatbot VALUES (5,"courses offered","We offer a variety of courses in fields such as Engineering, Management, Arts, Science, and more. For a full list, visit our website or specify a field of interest.	");
INSERT into chatbot VALUES (6,"application deadline ","The application deadline varies by course. Please let us know which program you’re interested in for accurate dates.	");
INSERT into chatbot VALUES (7,"fee structure","The fee structure depends on the program. Please specify the course to get detailed fee information.	");
INSERT into chatbot VALUES (8,"scholarships","We offer merit-based and need-based scholarships. Please visit our scholarships page for details or provide specific information to check your eligibility.	");
INSERT into chatbot VALUES (9,"entrance exam","For some courses, entrance exams are required. Please specify the course to know about the exam details and syllabus.	");
INSERT into chatbot VALUES (10,"hostel facilities","Yes, we provide hostel facilities with amenities like Wi-Fi, mess, and 24/7 security. Separate hostels are available for boys and girls.	");
INSERT into chatbot VALUES (11,"contact details","You can contact us at (033) 2482 0676/0670/0641 or contact@bbit.edu.in. Alternatively, visit our website for more details.	");
INSERT into chatbot VALUES (12,"placement","We have a strong placement record with top companies visiting our campus. For specific stats, please refer to our placement page.	");
INSERT into chatbot VALUES (13,"document requirements","Common documents include previous academic certificates, ID proof, passport-sized photos, and any entrance exam scorecards. Please confirm based on your course.	");
INSERT into chatbot VALUES (14,"part-time courses","We offer part-time and online courses in various fields. Please specify your area of interest for more details.	");
INSERT into chatbot VALUES (15,"admission status","To check your admission status, please provide your application ID or registered email.	");
INSERT into chatbot VALUES (16,"refund policy","The refund policy varies based on the stage of admission. Please refer to our terms and conditions or contact the admissions office.	");
INSERT into chatbot VALUES (17,"international students","Yes, we welcome international students. Please visit our international admissions page for visa and course requirements.	");
INSERT into chatbot VALUES (18,"hi","Hello! How can I assist you with admission-related queries today?	");
INSERT into chatbot VALUES (19,"hello","Hello! How can I assist you with admission-related queries today?	");
INSERT into chatbot VALUES (20,"how are you","I’m just a bot, but I’m here to help! What would you like to know about admissions?	");
INSERT into chatbot VALUES (21,"thank you ","You’re welcome! Let me know if you have any other questions.	");
INSERT into chatbot VALUES (22,"thanks","You’re welcome! Let me know if you have any other questions.	");
INSERT into chatbot VALUES (23,"goodbye","Goodbye! Have a great day! Feel free to reach out if you have more questions.	");
INSERT into chatbot VALUES (24,"bye","Goodbye! Have a great day! Feel free to reach out if you have more questions.	");
INSERT into chatbot VALUES (25,"admission open","Admissions are currently open for several programs. Please specify the course for details.	");
INSERT into chatbot VALUES (26,"address","We are located at Nischintapur, Budge Budge, kolkata - 700137, West Bengal, India. Visit our website for a map and directions.	");
INSERT into chatbot VALUES (27,"location","We are located at Nischintapur, Budge Budge, kolkata - 700137, West Bengal, India. Visit our website for a map and directions.	");
INSERT into chatbot VALUES (28,"facilities","Our campus offers modern classrooms, labs, libraries, sports complexes, and more.	");
INSERT into chatbot VALUES (29,"placement companies","Companies like Tech Mahindra, IBM, WIPRO, INFOSYS visit our campus for recruitment.	");
INSERT into chatbot VALUES (30,"working hours","Our admission office is open from 9 AM to 5 PM, Monday to Saturday.	");
INSERT into chatbot VALUES (31,"holidays","The admission office remains closed on Sundays and public holidays.	");
INSERT into chatbot VALUES (32,"campus visit","You’re welcome to visit our campus! Please schedule an appointment with our admissions office.	");
INSERT into chatbot VALUES (33,"transportation","We provide bus services for students and staff from various city locations.	");
INSERT into chatbot VALUES (34,"about the institute","[Institute Name] is known for academic excellence and holistic student development.	");
INSERT into chatbot VALUES (35,"best course","The best course depends on your interest and career goals. Let us know your preferences.	");
INSERT into chatbot VALUES (36,"required percentage","The required percentage varies by course. For most programs, a minimum of 50-60% is needed.	");
INSERT into chatbot VALUES (37,"online classes","Yes, we offer online and hybrid learning options for certain programs.	");
INSERT into chatbot VALUES (38,"payment options","You can pay via online transfer, credit/debit cards, or at the campus admission office.	");
INSERT into chatbot VALUES (39,"part time jobs","We assist students in finding part-time jobs through our career services team.	");
INSERT into chatbot VALUES (40,"documents missing","If any documents are missing, please contact the admissions office for further assistance.	");
INSERT into chatbot VALUES (41,"issue","	I’m sorry to hear that. Could you please describe the issue in detail so I can assist you better?	");
INSERT into chatbot VALUES (42,"problem","	I’m sorry to hear that. Could you please describe the issue in detail so I can assist you better?	");
INSERT into chatbot VALUES (43,"deadline extension","	Deadlines can sometimes be extended. Please contact the admissions office for updates.	");
INSERT into chatbot VALUES (44,"confused","	No worries! I’m here to help. Could you let me know what you’re looking for?	");
INSERT into chatbot VALUES (45,"error ","	I’m sorry to hear that. Could you please describe the issue in detail so I can assist you better?	");
INSERT into chatbot VALUES (46,"don’t know","	No worries! I’m here to help. Could you let me know what you’re looking for?	");
INSERT into chatbot VALUES (47,"why no response","	Apologies for the delay. How can I assist you now?	");
INSERT into chatbot VALUES (48,"fee too high","	We understand your concern. Scholarships and installment options are available for eligible students.	");
INSERT into chatbot VALUES (49,"waiting","	I apologize for the delay. Let me check and get back to you.	");
INSERT into chatbot VALUES (50,"no reply","	I apologize for the delay. Let me check and get back to you.	");
INSERT into chatbot VALUES (51,"admission rejected	","	Please contact the admissions office for clarification and possible next steps.	");
INSERT into chatbot VALUES (52,"password","	Please use the 'Forgot Password' option or contact support to reset your credentials.	");
INSERT into chatbot VALUES (53,"forgot login","	Please use the 'Forgot Password' option or contact support to reset your credentials.	");
INSERT into chatbot VALUES (54,"late application","	Late applications might be considered on a case-by-case basis. Please contact the admissions office.	");
INSERT into chatbot VALUES (55,"fake information","	Providing accurate information ensures a smooth admission process. Kindly verify and resubmit any details.	");
INSERT into chatbot VALUES (56,"lost documents","	Please arrange for duplicate documents or contact the admissions office for alternatives.	");
INSERT into chatbot VALUES (57,"confirmation","	Check your spam folder or contact the admissions office to confirm your application status.	");
INSERT into chatbot VALUES (58,"no email","	Check your spam folder or contact the admissions office to confirm your application status.	");
INSERT into chatbot VALUES (59,"eligibility not met","	You can explore other programs or contact our counselors for guidance on alternatives.	");
INSERT into chatbot VALUES (60,"can’t find course","	Please share the course name or field of interest so I can assist you in locating it.	");
INSERT into chatbot VALUES (61,"not working","	We apologize for the inconvenience. Please try again later or contact support.	");
INSERT into chatbot VALUES (62,"server down","	We apologize for the inconvenience. Please try again later or contact support.	");
INSERT into chatbot VALUES (63,"confusing","	I understand it can be overwhelming. Let me simplify the process for you.	");
INSERT into chatbot VALUES (64,"too many steps","	I understand it can be overwhelming. Let me simplify the process for you.	");
INSERT into chatbot VALUES (65,"irrelevant answer","	I apologize if my response didn’t help. Could you clarify your question for a better answer?	");
INSERT into chatbot VALUES (66,"immediate assistance","	Please contact our helpline at [phone number] for urgent support.	");
INSERT into chatbot VALUES (67,"urgent help	","	Please contact our helpline at [phone number] for urgent support.	");
INSERT into chatbot VALUES (68,"unnecessary messages","	We ensure to provide only relevant information. Let us know if something needs correction.	");
INSERT into chatbot VALUES (69,"spam","	We ensure to provide only relevant information. Let us know if something needs correction.	");
INSERT into chatbot VALUES (70,"waiting list","	If you are on the waiting list, we will notify you of updates as soon as possible.	");
INSERT into chatbot VALUES (71,"refund delay","	Refunds typically take 7-10 business days. If delayed, contact the accounts office.	");
INSERT into chatbot VALUES (72,"response","	We apologize for missing your call. Please try again or email us at contact@bbit.edu.in.	");
INSERT into chatbot VALUES (73,"missed call","	We apologize for missing your call. Please try again or email us at contact@bbit.edu.in.	");
INSERT into chatbot VALUES (74,"admission denied","	Admission might be denied due to eligibility criteria. Contact us for clarification.	");
INSERT into chatbot VALUES (75,"seat availability","	Seat availability depends on the course. Please provide details to check current status.	");
INSERT into chatbot VALUES (76,"placement guarantee","	While we have excellent placement support, securing a job depends on individual performance.	");
INSERT into chatbot VALUES (77,"campus visit","	Yes, campus tours are available. You can schedule a visit through our website.	");
INSERT into chatbot VALUES (78,"hostel accommodation ","	Yes, we provide hostel facilities for both boys and girls	");
INSERT into chatbot VALUES (79,"specialization","	We offer specializations in various fields. You can choose your specialization in the second or third year of study.	");
INSERT into chatbot VALUES (80,"Wi-Fi","	We offer high-speed Wi-Fi across the campus, spacious study areas, and well-maintained cafeterias for students.	");
INSERT into chatbot VALUES (81,"medical assistance","	We have medical facilities, health services, and counseling support available for all students.	");
INSERT into chatbot VALUES (82,"application status","	You can check your application status on our admissions portal by logging in with your credentials.	");
INSERT into chatbot VALUES (83,"hiring companies","	We have partnerships with leading companies such as IBM, TCS, Cognizant, Wipro etc. The complete list of our recruiters is available on our website.	");
INSERT into chatbot VALUES (84,"internship","	We facilitate internship opportunities with top organizations to give students hands-on experience and industry exposure.	");
INSERT into chatbot VALUES (85,"placement drives	","	We host regular placement drives and career fairs where students can interact with top recruiters.	");
INSERT into chatbot VALUES (86,"placement statistics","	Our placement statistics are published annually, with a high success rate across various programs. Visit our website for detailed reports	");
INSERT into chatbot VALUES (87,"contact, support","	You can reach out to our admissions office through mail id contact@bbit.edu.in	");
INSERT into chatbot VALUES (88,"safety","	The campus is monitored round-the-clock with CCTV cameras and trained security personnel to ensure safety.	");
INSERT into chatbot VALUES (89,"security","	The campus is monitored round-the-clock with CCTV cameras and trained security personnel to ensure safety.	");
INSERT into chatbot VALUES (90,"green campus","	We take pride in being an eco-friendly campus with greenery, solar power, rainwater harvesting, and waste management systems.	");
INSERT into chatbot VALUES (91,"housekeeping","	Hostels include housekeeping and regular maintenance for student convenience.	");
INSERT into chatbot VALUES (92,"mess","	We have clean and hygienic food courts and mess facilities offering nutritious meals	");
INSERT into chatbot VALUES (93,"playground","	Our campus has a fully-equipped gym, a swimming pool, a running track, and courts for basketball, badminton, cricket, and more.	");
INSERT into chatbot VALUES (94,"gym","	Our campus has a fully-equipped gym, a swimming pool, a running track, and courts for basketball, badminton, cricket, and more.	");
INSERT into chatbot VALUES (95,"sports","	Our campus has a fully-equipped gym, a swimming pool, a running track, and courts for basketball, badminton, cricket, and more.	");
INSERT into chatbot VALUES (96," hostel facilities","	Hostels are well-maintained with single, double, and triple occupancy rooms. Rules and fee details are on our website.	");
INSERT into chatbot VALUES (97,"hostel contact","	You can contact the hostel warden at warden@bbit.edu.in for any accommodation-related assistance	");
INSERT into chatbot VALUES (98,"hostel fees","	Hostel fees vary depending on room type. Please check the hostel section on our website for detailed fee structure.	");
INSERT into chatbot VALUES (99,"hostel admission","	ou can apply for hostel accommodation while filling out your admission form. A separate hostel application is also available online.	");
INSERT into chatbot VALUES (100,"power backup","	All hostels have 24/7 electricity with power backup systems to ensure continuous supply	");
INSERT into chatbot VALUES (101,"hostel timing","	Students must return to the hostel by the designated curfew time. Night-outs are allowed with prior permission from the warden.	");
INSERT into chatbot VALUES (102,"parents visit","	Parents and local guardians can visit during visiting hours. Overnight stay is not permitted for guests in student rooms.	");
INSERT into chatbot VALUES (103,"hostel allotment","	Hostel rooms are allotted on a first-come, first-served basis after admission confirmation. You can request preferred occupancy during application.	");
INSERT into chatbot VALUES (104,"distance from campus","	Our hostels are located within the campus or just adjacent to it, making it easy for students to access all college facilities.	");
